@startuml
actor Customer as C
participant ReserveSystem as Rs
participant Branch as Br
participant Room as R
participant Booking as B



C -> Rs: booking_room(room _id)
activate Rs
loop [for each room in branch]
    Rs -> Br: get_room(room_id)
    activate Br
    Br -> R:find_room
    activate R
    end
R -> Br: room instance
deactivate R
Br -> Rs: room instance
deactivate Br
Rs -> B: create booking(customer_id, room_id)
activate B
B --> Rs:booking instance
deactivate B
Rs --> C: booking_complete
deactivate Rs







    




@enduml