@startuml
autoactivate on

actor "Customer" as Program
participant "ReserveSystem\n(Controller)" as System
participant "Customer" as Customer
participant "Booking" as Booking
participant "Policy" as Policy
participant "Room" as Room
participant "Equipment" as Equipment
participant "Payment" as Payment
participant "PaymentChannel" as Channel

title Cancellation Process

Program -> System : process_cancellation(customer_id, booking_id)

    loop [in self.customer_list]
        System -> Customer : get_id()
        Customer --> System : return {customer_id : str}
    end

    alt [Customer Match Found]
        
        System -> Customer : get_transaction_list()
        Customer --> System : return {booking_list : List<Booking>}

        loop [in booking_list]
            System -> Booking : get_booking_id()
            Booking --> System : return {fetched_booking_id : str}
        end

        alt [Booking Match Found]
            
            System -> Policy : check_cancel_rule(currenttime,starttime,member)
            Policy -> Customer : get_cancellation_limit_hours()
            Customer --> Policy : return {cancellation_limit_hours(6,12,24)}
            Policy --> System : return {isAllowed: bool, refund_amount: float}

            alt [isAllowed == true]
                
                System -> Booking : change_booking_status(CANCELLED)
                Booking --> System : retuem {status_updated : bool}

                loop
                System -> Booking : get_room()
                Booking --> System : return {target_room : Room}
                end

                System -> Room : update_room_status(AVAILABLE)
                Room --> System : return {void}

                loop
                System -> Booking : get_equipment_list()
                Booking --> System : return {eq_list : List<Equipment>}
                end

                loop [in eq_list]
                    System -> Equipment : set_status(AVAILABLE)
                    return void
                end

                System -> Payment : process_payment(refund_amount,payment_channel)
                    Payment -> Channel : process(refund_amount,payment_channel)
                    return process_status : bool
                return payment_success : bool
                
                System --> Program : return {cancellation_success : bool}

            else [isAllowed == false]
                System --> Program : return "Error: Policy Violation"
            end

        else [Booking Not Found]
            System --> Program : return "Error: Booking Not Found"
        end

    else [Customer Not Found]
        System --> Program : return "Error: Customer Not Found"
    end

@enduml