@startuml

skinparam style strictuml
skinparam sequenceMessageAlign center

actor "Staff" as staff
participant "ReserveSystem" as system
participant "Customer" as customer
participant "Service_IN" as sv_in
participant "Booking" as booking
participant "Room" as room
participant "Equipment" as eq
participant "TimeSlot" as timeslot


staff -> system :Checkin(customer_id, reserve_id)
activate system

loop search_customer(customer_id)
    system -> customer :get_customer(customer_id)
    activate customer
    alt found
        customer --> system : return Customer (instance)
    else not found
        customer --> system : "Not found Customer in System"
    end
end

system -> customer : get_reserve_detail(reserve_id)
loop search_reserve(reserve_id)
    customer -> sv_in :get_reserve(reserve_id)
   alt found 
        sv_in --> customer : Reserve (instance)
    else not found
        sv_in --> customer : "Not Found Reserve"
    end
end
customer --> system : reserve_info

system -> sv_in : get_checkin()
activate sv_in
loop for booking in booking_list
    sv_in -> booking : get_booking_detail()
    activate booking

    booking -> room : get_room_reserve_detail()
    activate room
    room -> timeslot : update_status(time_booking)
    activate timeslot
    timeslot --> room : update status "OCCUPIED" success
    deactivate timeslot
    room --> booking : room_info
    deactivate room

    loop for eq in equipment_list
        booking -> eq: get_equipment_reserve_detail()
        activate eq
        eq -> timeslot : update_status(time_booking)
        activate timeslot
        timeslot --> eq : update status "OCCUPIED" success
        deactivate timeslot
        eq --> booking : eq_info()
        deactivate eq
    end
    booking --> sv_in : booking_info
    deactivate booking
end
sv_in --> system : check-in success
deactivate sv_in
deactivate customer
system --> staff : CHECKIN SUCCESSFULLY!
deactivate system


