@startuml
title Daily Report

actor Staff as Staff
participant ReserveSystem as System
participant Customer as Customer 
participant Transaction as Service
participant Room as RoomDB
participant Equipment as EquipmentDB
participant Service_OUT as Service_OUT


Staff -> System : requestDailyReport(date)
activate System
loop [for id in Customer_list]
    System -> Customer : find_Customer_id()
    activate Customer
    Customer --> System : return Customer (instant)
    end

System -> Customer : getDailyRevenueData
Customer -> Service : getDailyRevenue(date)
activate Service
Service --> Customer

Customer --> System  : revenueData
System -> Customer: get_transaction
Customer -> Service : get_transaction_info
loop [for room in room_list]
Service -> RoomDB : getRoomStatus(date)
    activate RoomDB
    RoomDB --> Service 
    ' Service --> Customer
    ' Customer --> System : statusData
    deactivate RoomDB
    end

' Customer -> Service : getDailyRevenue(date)
' Service --> Customer
' Customer --> System  : revenueData
' deactivate Customer

loop [for eq in equipment_list]
    Service  -> EquipmentDB : getEquipmentStatus(date)
    activate EquipmentDB
    EquipmentDB --> Service
    deactivate EquipmentDB
    end
' Service --> Customer
' activate Customer
' Customer --> System : statusData
' deactivate Customer

' opt Penalty & Notes
loop [for p in penalty_list]
    Service -> Service_OUT : getAllPenalties(date)
    activate Service_OUT
    Service_OUT --> Service 
    deactivate Service_OUT
    end
    ' activate Customer
    ' deactivate Customer
' end
Service --> Customer : return transaction_info
deactivate Service
Customer --> System : return transaction
deactivate Customer
System -> System : generateDailyReport()
System --> Staff : dailyReport
deactivate System

@enduml
