@startuml

skinparam style strictuml
skinparam sequenceMessageAlign center

actor "Customer" as actor
participant "ReserveSystem" as system
participant "Branch" as branch
participant "Customer" as customer
participant "Room" as room
participant "StockEquipment" as stock
participant "Equipment" as eq
' participant "Booking" as booking
' participant "Service_IN" as sv_in
participant "TimeSlot" as timeslot

actor -> system : select_eq(customer_id,branch_id,room_id,eq_list,day,s_time,e_time)
activate system
loop search_customer(customer_id)
    system -> customer : get_customer_info(customer_id)
    activate customer
    customer --> system : Customer
    deactivate customer
end
loop search_branch(branch_id)
    system -> branch : get_room_quota(room_id)
    activate branch
    loop search_room(room_id)
                branch -> room : get_eq_quota(room_id)
                activate room
                room --> branch : eq_quota_max
                deactivate room
    end
    branch --> system : eq_quota_max
end
deactivate branch
loop for eq_id in eq_list
    ' --- ขั้นตอนที่ 1: การตรวจสอบ (Check) ---
    system -> branch : check_can_reserve(eq_id,day,s_time,e_time)
    activate branch
    branch -> stock : verify_available(eq_id,day,s_time,e_time)
    activate stock
    stock -> stock : get_eq(eq_id) :Equipment
    ' stock --> stock : Equipment
    ' eq--> stock : Equipment
    stock -> eq : check_status(day,s_time,e_time)
    activate eq
    eq --> stock : status
    deactivate eq

    alt status is "Available"
        stock --> branch : Status Available
        branch --> system : Can Reserve
        
        ' --- ขั้นตอนที่ 2: การดึงข้อมูล (Get) เมื่อตรวจสอบผ่านแล้ว ---
        system -> branch : get_size_eq(eq_id)
        branch -> stock : find_and_get_size(eq_id)
        
        loop for eq in equipment_list
            stock -> eq : verify_id(eq_id)
            activate eq
            alt eq_id == eq.id
                eq --> stock : MATCH
                stock -> eq : get_size()
                eq --> stock : size
            else
                eq --> stock : NOT MATCH
            end
            deactivate eq
        end
        
        stock --> branch : size (or 0)
        branch --> system : size
        system -> system : total_requested_size += size
        
    else status not "Available"
        stock --> branch : Not Ready
        branch --> system : Cannot Reserve (Skip)
    end
    
    deactivate stock
    deactivate branch
end
activate branch


alt total_requested_size <= quota_eq_max
    system --> actor : Can Reserve Equipment - Add to Booking Successfully
else total_requested_size > quota_eq_max
    system --> actor : Exceed Room Quota Limit
end

deactivate system

@enduml