@startuml

skinparam style strictuml
skinparam sequenceMessageAlign center

actor "Actor" as user_actor
participant "ReserveSystem" as system
participant "User" as user

user_actor -> system : login(user_name, password)
activate system
system -> user : get_user_password(user_name)
activate user
user --> system : user_password
deactivate user
system -> system : verify_password(input_password, hashed_password)
    alt #LightBlue [PasswordCorrect]
        system --> user_actor : Login Successfully
    else #LightPink [PasswordIncorrect]
        system --> user_actor : Incorrect Password
    end
deactivate system

@enduml