@startuml
title SD-06: add_product_to_service_out

actor Customer as C
participant "RhythmReserve" as RR
participant "Customer" as CUS
participant "Booking" as BK
participant "Branch" as BR
participant "StockProduct" as STCK
participant "ServiceOUT" as SOUT

C -> RR : add_product_to_service_out(branch_id, customer_id,\nreserve_id, booking_id, product_type, amount)
activate RR
RR -> RR : get_branch_by_id(branch_id)
RR -> RR : get_customer_by_id(customer_id)

RR -> CUS : get_reserve(reserve_id)
activate CUS
CUS -->> RR : reserve

RR -> CUS : find_booking(booking_id)

CUS -->> RR : booking
deactivate CUS

RR -> BK : service_out
activate BK
BK -->> RR : service_out
deactivate BK

RR -> BR : branch.product (get list)
activate BR
BR -->> RR : stock_list
deactivate BR

loop for stock in stock list
    alt stock.type == product_type
        RR -> RR : stock (found)
    end
end

alt stock is None
    RR --> C : raise Exception("Product type not found")
else len(stock.get_stock) < amount
    RR --> C : raise Exception("Not enough stock")
else
    loop i in range(amount)
        RR -> STCK : get_stock[0]
        activate STCK
        STCK --> RR : product

        RR -> SOUT : add_product(product)
        activate SOUT
        SOUT -> SOUT : __product_list.append(product)

        RR -> STCK : del_stock(product.id)
        STCK -> STCK : __product_list.pop(index)
        STCK --> RR : True
        deactivate STCK
    end

    RR -> SOUT : calculate_total_price()
    SOUT -> SOUT : sum(product.price) + sum(penalty.amount)
    SOUT --> RR : total_price
    deactivate SOUT

    RR --> C : { sout_id, products, total_price }
deactivate RR
end


@enduml
