@startuml
title SD-08: customer_check_out & Payment Confirmation

skinparam Style strictuml
skinparam MaxMessageSize 150
skinparam sequence {
    MessageAlignment center
    ParticipantPadding 15
}

actor Staff as S
participant "RhythmReserve" as RR
participant "Customer" as CUS
participant "Staff" as ST
participant "Booking" as BK
participant "Policy" as POL
participant "ServiceOUT" as SOUT
participant "PaymentServiceOut" as PSOUT
participant "DailyReport" as RPT

S -> RR : pay_service_out(...)
activate RR

activate CUS
RR -> CUS : get_reserve(reserve_id)
CUS -> RR : reserve
RR -> CUS : find_booking(booking_id)
CUS -> RR : booking
deactivate CUS

RR -> BK : get_service_out()
activate BK
BK -> RR : service_out
deactivate BK

RR -> RR : get_daily_report(booking.day, branch)
activate RR 
RR -> RR : report
deactivate RR

RR -> ST  : <<create>> Staff(...)
activate ST
ST -> RR : staff
deactivate ST

RR -> ST : customer_check_out(...)
activate ST
    
ST -> POL : check_late_checkout(...)
activate POL
POL -> ST : late_penalty
deactivate POL

alt late_penalty is not None
    ST -> SOUT : add_penalty(late_penalty)
end

alt damage found
    ST -> BK : update_status(MAINTENANCE)
    ST -> POL : check_damage_penalty(...)
    activate POL
    POL -> ST : penalty
    deactivate POL
    ST -> SOUT : add_penalty(penalty)
else
    ST -> BK : update_status(AVAILABLE)
end

ST -> PSOUT : <<create>> PaymentServiceOut(...)
activate PSOUT
PSOUT -> ST : payment_sout
deactivate PSOUT

ST -> PSOUT : calculate_total()
activate PSOUT
PSOUT -> SOUT : calculate_total_price()
activate SOUT
SOUT -> PSOUT : total_price
deactivate SOUT
PSOUT -> ST : void
deactivate PSOUT

loop for each penalty
    ST -> RPT : add_penalty(penalty)
end

ST -> RPT : add_booking_record(booking)
ST -> RR : payment_sout
deactivate ST
RR -> RR : confirm_checkout(payment_sout, report)
activate RR 
RR -> PSOUT : process_payment()
activate PSOUT
PSOUT -> RR : success
deactivate PSOUT

alt success is True
    RR -> RPT : add_revenue(total_price)
end

RR -> RR : formatted_data
deactivate RR

RR -> S : formatted_data
deactivate RR

@enduml