@startuml
title SD-09: manual_redeem_coupon

skinparam Style strictuml
skinparam MaxMessageSize 150
skinparam sequence {
    MessageAlignment center
    ParticipantPadding 20
}

actor Customer as C
participant "RhythmReserve" as RR
participant "Customer" as CUS
participant "Standard" as STD
participant "Premium" as PRM
participant "Diamond" as DMN
participant "Coupon" as CPN

C -> RR : manual_redeem_coupon(customer_id, points)
activate RR

RR -> RR : get_customer_by_id(customer_id)
activate RR 
RR -> RR : customer
deactivate RR

alt customer is Standard
    alt points != 20
        RR -> C : raise Exception("Standard รองรับเฉพาะ 20 แต้ม")
    else points == 20
        RR -> STD : redeem_coupon()
        activate STD
        STD -> STD : check points >= 20
        STD -> CPN : <<create>> Coupon(0.05)
        activate CPN
        CPN -> STD : coupon
        deactivate CPN
        STD -> RR : coupon
        deactivate STD
    end

else customer is Premium
    RR -> PRM : redeem_coupon(points)
    activate PRM
    alt Valid Points & Balance
        PRM -> CPN : <<create>> Coupon(discount_rate)
        activate CPN
        CPN -> PRM : coupon
        deactivate CPN
        PRM -> RR : coupon
    else Invalid
        PRM -> RR : raise Exception("แต้มไม่พอหรือตัวเลือกไม่ถูกต้อง")
    end
    deactivate PRM

else customer is Diamond
    RR -> DMN : redeem_coupon(points)
    activate DMN
    alt Valid Points & Balance
        DMN -> CPN : <<create>> Coupon(discount_rate)
        activate CPN
        CPN -> DMN : coupon
        deactivate CPN
        DMN -> RR : coupon
    else Invalid
        DMN -> RR : raise Exception("แต้มไม่พอหรือตัวเลือกไม่ถูกต้อง")
    end
    deactivate DMN
end

RR -> CUS : add_coupon(coupon)
activate CUS
CUS -> CUS : append to __coupon_list
CUS -> RR : void
deactivate CUS

RR -> C : coupon object
deactivate RR

@enduml