@startuml


class ReserveSystem{
    -branch_list : list
    -user_list : list
    -policy : class
    +add_user()
    +search_user()
    +get_transaction()
    +process_cancellation()
    +create_reservation()
    +notify_user()
    +update_room_status()
    +make_customer_id() : str
    +make_branch_id(name) : str
    
}

class Branch{
    -name : str
    -id : str
    -room_list : list
    -officer_list : list
    -equipment_list : list
    +id(): str
    +name() : str
    +room() : list
    +room(new_room) : void
    +equipment() : list
    +equipment(new_equipment) : void
    +get_available_slot(size, date) : list
    
}

class RoomStatus <<enumeration>>{
    AVAILABLE
    RESERVED
    OCCUPIED
    MAINTENANCE
}
class Room {
    -room_id : str
    -time_slot : list
    -size : str
    -rate : float
    -eq_quota : int
    -size : str
    -room_status : enum
}


class Time_slot{
    -start_time : str
    -end_time : str
    -status : str
}


class Equipment{
    -eq_id : str
    -time_slot : class
    -size : int
    +id() : str
}



class BookingStatus <<enumeration>> {
    ORDERED
    CONFIRMED
    CANCELLED
}

class Booking {
    -booking_id : str
    -customer : class
    -time_slot : class
    -equipment_list : list
    -created_at : datetime
    -status : Enum
    -price : float

    +add_equipment() : void
    +remove_equipment(): void
    +change_room() : void
    +change_time_slot() : void
    +calculate_price() : float
    +change_booking_status() : void
}

class OrderStatus <<enumeration>> {
    PENDING_PAYMENT
    PAID
    CANCELLED
    REFUNDED
}

class Order{
    -customer : class
    -booking_list : list
    -total_price : float
    -coupon : Coupon

    +add_booking() : void
    +remove_booking() : void

    +calculate_total() : float
    +apply_coupon() : void

    +change_status() : void
}


class PaymentChannel{
    +process() : bool
}

class QrScan{
    -qr_image : str
    +generate_qr()
}

class CreditCard{
    -card_number : str
    -cvv : str
    +validate_card()
}

class Payment{
    -order : class
    -coupon : class
    -fine : class
    -refund : class
    -payment_channel : class
    -payment_status : str
    -amount : float
    +process_payment()
    +payment_refund()

}
class TransStatus <<enumeration>> {
    PENDING
    CHECK_IN
    COMPLETED
    CANCELLED
    FAILED
}
class Transaction{
    -transaction_id : str
    -timestamp : datetime
    -order : class
    -type : str
    +check_cancel_rule()

    -status : enum
    +check_cancel_rule()
    +do_checkin()
    +do_checkout()
    +get_reserve_detail()
}

class UserRole <<enumeration>> {
    ADMIN
    STAFF
    CUSTOMER
}

class User{
    -user_id : str
    -username : str
    -password : str
    -name : str
    -email : str
    -phone : str
    -age : int
    -transaction_ls : list
    -role : enum
    +log_in()
    +log_out()
    +verify_password()
    +update_profile()
    +change_password()
    +add_transaction()
    +search_transaction()

}

class Officer{
    -brance_id : str
    -history_working : list
}

class BranchManager{
    -All_staff : list
    +add_staff()
    +remove_staff()
    +get_report()
    +approve_maintenance_request()
    +set_status(room_id, status) : void

}

class FrontDesk{
    -daily_report : list
    +add_equipment()
    +add_Daily_report()
    +customer_check_in()
    +customer_check_out()
}

class SystemAdmin{
    +add_coupon()
    +add_Room()
    +add_Branch()
    +Manage_membership_level()
    +Manage_booking_rules_and_penalties()
    +Mansge_Pricing()
    +make_equipment_id(branch_id, type_)
    +make_room_id(branch_id, size)
}

class Customer{
    -current_points : int
    -booking_history : list
    -my_coupon : list
    +redeem_point()
    +Booking_room()
    +Report_room()
    +view_membership_and_privileges()
}

class Standard{
    -recive_point_per_hr : int (3)
    +redeem_point()
    +get_cancellation_limit_hours() : int { return 24 }
}

class Premium{
    -recive_point_per_hr : int (5)
    +redeem_point()
    +get_cancellation_limit_hours() : int { return 12 }
}

class Diamond{
    -recive_point_per_hr : int (8)
    +redeem_point()
    +get_cancellation_limit_hours() : int { return 6 }
}

class PenaltyType <<enumeration>> {
    NO_SHOW
    CANCEL_LATE
    DAMAGE
}

class PenaltyStatus <<enumeration>> {
    PENDING      
    APPLIED      
    WAIVED       
}

class Penalty {
    -date :str
    -amount :float
    -reason :str
    - penalty_id : str
    - type : Enum 
    - rate : float 
    - fixed_amount : float
    - created_at : datetime
    - status : Enum 
    - booking : Booking
    +change_penalty_status()
}

class Policy{
    - policy_id : str
    - name : str
    -penalty_list : list
    - description : str
    - cancel_before_hours : int
    - refund_rate : float
    - no_show_rate : float
    - active : bool
    +check_cancel_rule() : void
    +get_all_penalty() : void
    +add_penalty() : void
    + calculate_penalty() : class
    + calculate_refund() : float
    + is_refundable() : bool
}

class NotiStatus <<enumeration>>{
    PENDING
    SENT
    FAILED
}
class Notification{
    -notification_id: str
    -user : str
    -order : class
    -message: str
    -is_read: bool
    -status : enum
    +send()
    +format_massage()
    +mark_as_read()
    +retry_send()
}


class Coupon{
    -All_coupon : list
    -expired_date : datetime
    -discount : float
    +create_coupon()

}

class RoomType <<enumeration>>{
    S
    M
    L
    XL
}

class EquipmentType <<enumeration>> {
    ELECTRICGUITAR
    ACOUSTICGUITAR
    DRUM
    MICROPHONE
    BASS
    KEYBOARD
}

class RoomEquipmentStatus <<enumeration>> {

}



User <|-- Officer
User <|-- Customer
Customer <|-- Standard
Customer <|-- Premium
Customer <|-- Diamond
Officer <|-- BranchManager
Officer <|-- FrontDesk
Officer <|-- SystemAdmin
Payment <|-- PaymentChannel 
PaymentChannel <|-- QrScan
PaymentChannel <|-- CreditCard
ReserveSystem o-- Branch
ReserveSystem o-- Policy
Customer o-- Coupon
Branch o-- Room
Branch o-- Equipment
Room o-- Time_slot
Equipment o-- Time_slot
Customer o-- Order
Order o-- Booking
Customer o-- Transaction
Customer o-- Notification
Order <-- Payment
Room --* RoomType
Equipment --* EquipmentType 
@enduml